/**
 * Datacenter mode mock data for OpsHub / Fithub.
 * Mirrors the exact TypeScript types used by the factory mode data in useOpshubMockData.ts.
 * Imported by useOpshubMockData when platformMode === 'datacenter'.
 */

import type {
    ActivityEntry,
    AIAgentRecommendation,
    ChangelogEntry,
    ChecklistStep,
    DetectedAnomaly,
    DiscussionComment,
    ExecutionChecklist,
    Factory,
    OpshubPost,
    TeamMember,
    WorkflowRepo,
    WorkOrderCard,
    WorkOrderTask,
} from '@/lib/types/opshub'

// ─── Team ─────────────────────────────────────────────────────────────────
export const DC_MOCK_TEAM: TeamMember[] = [
    { id: 'sarah-chen',    name: 'Sarah Chen',       role: 'DC Operations Manager',     facility: 'Frankfurt DC Campus', avatarInitials: 'SC', avatarColor: '#3B82F6', status: 'available' },
    { id: 'omar-khalid',   name: 'Omar Khalid',      role: 'Infrastructure Engineer',    facility: 'Frankfurt DC Campus', avatarInitials: 'OK', avatarColor: '#10B981', status: 'available' },
    { id: 'ahmed-nasser',  name: 'Ahmed Nasser',     role: 'Systems Lead',              facility: 'Frankfurt DC Campus', avatarInitials: 'AN', avatarColor: '#EF4444', status: 'available' },
    { id: 'lisa-park',     name: 'Lisa Park',        role: 'Network Engineer',           facility: 'Frankfurt DC Campus', avatarInitials: 'LP', avatarColor: '#EC4899', status: 'in-field' },
    { id: 'fahad-alrashid',name: 'Fahad Al-Rashid',  role: 'DC Operations Manager',     facility: 'Riyadh Data Center',  avatarInitials: 'FA', avatarColor: '#8B5CF6', status: 'available' },
    { id: 'ai-agent',      name: 'AI Agent',         role: 'System',                    facility: 'Frankfurt DC Campus', avatarInitials: '🤖', avatarColor: '#A855F7', status: 'available', isAI: true },
]

// ─── Factories (Data Centers) ─────────────────────────────────────────────
export const DC_MOCK_FACTORIES: Factory[] = [
    {
        id: 'dc-frankfurt',
        name: 'frankfurt',
        displayName: 'Frankfurt DC Campus',
        location: 'Germany',
        avatar: '🖥️',
        metrics: { efficiency: 96.8, uptime: 99.99, activeWorkflows: 18, resolvedAnomalies: 94 },
    },
    {
        id: 'dc-singapore',
        name: 'singapore',
        displayName: 'Singapore Cloud Hub',
        location: 'Singapore',
        avatar: '☁️',
        metrics: { efficiency: 98.1, uptime: 99.999, activeWorkflows: 27, resolvedAnomalies: 142 },
    },
    {
        id: 'dc-newyork',
        name: 'newyork',
        displayName: 'New York Exchange DC',
        location: 'USA',
        avatar: '⚡',
        metrics: { efficiency: 91.3, uptime: 99.95, activeWorkflows: 31, resolvedAnomalies: 67 },
    },
    {
        id: 'dc-riyadh',
        name: 'riyadh',
        displayName: 'Riyadh Data Center',
        location: 'Saudi Arabia',
        avatar: '🏗️',
        metrics: { efficiency: 94.2, uptime: 99.6, activeWorkflows: 14, resolvedAnomalies: 52 },
    },
    {
        id: 'dc-tokyo',
        name: 'tokyo',
        displayName: 'Tokyo HPC Center',
        location: 'Japan',
        avatar: '🔬',
        metrics: { efficiency: 97.4, uptime: 99.99, activeWorkflows: 35, resolvedAnomalies: 201 },
    },
    {
        id: 'dc-saopaulo',
        name: 'saopaulo',
        displayName: 'São Paulo Edge DC',
        location: 'Brazil',
        avatar: '🌿',
        metrics: { efficiency: 92.7, uptime: 99.8, activeWorkflows: 11, resolvedAnomalies: 38 },
    },
]

// ─── Workflow Repositories ─────────────────────────────────────────────────
export const DC_MOCK_REPOS: WorkflowRepo[] = [
    { id: 'dc-repo-1',  factoryId: 'dc-frankfurt', name: 'UPS Battery Failure Detection',       description: 'ML-based UPS battery degradation prediction with 72h advance notice and automatic work order creation', stars: 5, forks: 4, isPublic: true, tags: ['ups', 'predictive', 'SOP-P-047'], language: 'Power', lastUpdated: '2026-02-12T10:30:00Z', createdAt: '2025-08-10T08:00:00Z' },
    { id: 'dc-repo-2',  factoryId: 'dc-frankfurt', name: 'Cooling System Optimization',         description: 'AI-driven CRAC/CRAH scheduling that reduced PUE from 1.41 to 1.22 in Q4 2025', stars: 5, forks: 3, isPublic: true, tags: ['cooling', 'energy', 'SOP-C-007'], language: 'Cooling', lastUpdated: '2026-02-07T14:20:00Z', createdAt: '2025-06-22T09:00:00Z' },
    { id: 'dc-repo-3',  factoryId: 'dc-frankfurt', name: 'Server Hardware Failure Prediction',  description: 'Predictive failure analysis for drives, PSUs and memory based on SMART data and thermal trends', stars: 5, forks: 3, isPublic: true, tags: ['hardware', 'predictive', 'SOP-H-012'], language: 'Servers', lastUpdated: '2026-02-05T16:45:00Z', createdAt: '2025-04-10T11:00:00Z' },
    { id: 'dc-repo-4',  factoryId: 'dc-singapore', name: 'Rack Temperature Control',            description: 'Automated hot-aisle containment adjustment to maintain inlet temperatures below 27°C', stars: 4, forks: 2, isPublic: true, tags: ['thermal', 'cooling', 'SOP-T-003'], language: 'Thermal', lastUpdated: '2026-02-09T08:15:00Z', createdAt: '2025-07-01T07:00:00Z' },
    { id: 'dc-repo-5',  factoryId: 'dc-singapore', name: 'Capacity Planning Automation',        description: 'Real-time rack utilization monitoring with automated capacity alerts and procurement triggers', stars: 5, forks: 4, isPublic: true, tags: ['capacity', 'automation', 'SOP-C-015'], language: 'Operations', lastUpdated: '2026-02-08T11:30:00Z', createdAt: '2025-03-15T10:00:00Z' },
    { id: 'dc-repo-6',  factoryId: 'dc-singapore', name: 'Fiber Connectivity Audit',            description: 'Automated fiber link health checks with OTDR analysis and patch panel mapping validation', stars: 3, forks: 1, isPublic: true, tags: ['network', 'fiber', 'SOP-N-022'], language: 'Network', lastUpdated: '2026-02-06T09:00:00Z', createdAt: '2025-09-20T14:00:00Z' },
    { id: 'dc-repo-7',  factoryId: 'dc-newyork',   name: 'PDU Load Balancing',                  description: 'Real-time power distribution unit load monitoring with automated load migration between circuits', stars: 3, forks: 1, isPublic: true, tags: ['power', 'pdu', 'SOP-P-008'], language: 'Power', lastUpdated: '2026-02-04T13:00:00Z', createdAt: '2025-11-01T08:00:00Z' },
    { id: 'dc-repo-8',  factoryId: 'dc-newyork',   name: 'Security Incident Response',          description: 'Automated physical security incident triage with access log correlation and CCTV tagging', stars: 4, forks: 2, isPublic: true, tags: ['security', 'incident', 'SOP-S-011'], language: 'Security', lastUpdated: '2026-02-07T15:30:00Z', createdAt: '2025-06-18T12:00:00Z' },
    { id: 'dc-repo-9',  factoryId: 'dc-tokyo',     name: 'PUE Optimization Suite',              description: 'Comprehensive power usage effectiveness monitoring with automated cooling and power adjustments', stars: 5, forks: 5, isPublic: true, tags: ['pue', 'energy', 'SOP-E-001'], language: 'Energy', lastUpdated: '2026-02-09T06:00:00Z', createdAt: '2025-02-10T09:00:00Z' },
    { id: 'dc-repo-10', factoryId: 'dc-tokyo',     name: 'Firmware Update Pipeline',            description: 'Automated firmware patching for servers, switches and PDUs with rollback support', stars: 5, forks: 4, isPublic: true, tags: ['firmware', 'automation', 'SOP-F-001'], language: 'General', lastUpdated: '2026-02-08T22:00:00Z', createdAt: '2024-12-05T08:00:00Z' },
    { id: 'dc-repo-11', factoryId: 'dc-tokyo',     name: 'Diesel Generator Test Protocol',      description: 'Scheduled generator load bank testing with automated fail/pass logging and compliance reporting', stars: 4, forks: 3, isPublic: true, tags: ['generator', 'compliance', 'SOP-G-002'], language: 'Power', lastUpdated: '2026-02-06T18:00:00Z', createdAt: '2025-01-20T10:00:00Z' },
    { id: 'dc-repo-12', factoryId: 'dc-saopaulo',  name: 'Humidity Control Procedure',          description: 'Automated humidity regulation for server rooms to maintain 40–55% RH as per ASHRAE A2 guidelines', stars: 2, forks: 0, isPublic: true, tags: ['humidity', 'environment', 'SOP-E-012'], language: 'Environment', lastUpdated: '2026-02-03T11:00:00Z', createdAt: '2025-10-28T14:00:00Z' },
]

// ─── Feed Posts ───────────────────────────────────────────────────────────
export const DC_MOCK_FEED: OpshubPost[] = [
    {
        id: 'dc-post-1',
        type: 'anomaly_alert',
        authorType: 'ai_agent',
        authorId: 'dc-frankfurt',
        authorName: 'Frankfurt AI Monitor',
        title: 'Critical Alert: Rack C-14 Thermal Runaway Risk Detected',
        content: `**Rack C-14 (Row C, Frankfurt DC)** inlet temperature at **34.1°C** — 7.1°C above ASHRAE threshold.\n\n**Severity:** Critical\n**Recommended Action:** Inspect CRAC unit CR-03 immediately. Temporarily redistribute workloads from C-14 to C-08/C-09.\n**Pattern Source:** Matches cooling failure signature detected in NYC cluster (Jan 2026).`,
        anomalyRef: 'dc-anomaly-1',
        workflowRepoRef: 'dc-repo-4',
        tags: ['thermal', 'cooling', 'critical'],
        upvotes: 38,
        comments: 4,
        createdAt: '2026-02-13T08:30:00Z',
        status: 'pending',
    },
    {
        id: 'dc-post-2',
        type: 'insight',
        authorType: 'ai_agent',
        authorId: 'dc-singapore',
        authorName: 'Cross-DC AI',
        title: 'Singapore Cooling Optimization — PUE Dropped to 1.19',
        content: `**Singapore Cloud Hub** achieved PUE **1.19** this quarter — down from 1.31 using the new AI cooling schedule.\n\nKey factors:\n- Hot-aisle containment optimization (−8% cooling load)\n- Free cooling hours extended +3.2h/day via weather correlation\n- CRAC set-point adjustment from 18°C to 21°C supply temp\n\n**Estimated annual saving: $340k** in energy costs. Workflow available for adoption.`,
        workflowRepoRef: 'dc-repo-2',
        tags: ['pue', 'energy', 'cooling', 'best-practice'],
        upvotes: 61,
        comments: 9,
        createdAt: '2026-02-12T14:00:00Z',
        status: 'open',
    },
    {
        id: 'dc-post-3',
        type: 'anomaly_alert',
        authorType: 'human',
        authorId: 'omar-khalid',
        authorName: 'Omar Khalid',
        title: 'UPS-3 Battery Health Degraded — NYC Data Center',
        content: `Flagging anomaly from **New York Exchange DC**.\n\nUPS-3 battery string showing **67% state of health** (threshold: 80%). Estimated time to failure: 6–9 months at current discharge rate.\n\n**Observation:** Also detected increased float current — classic early indicator of cell sulfation.\n\nRecommend scheduling replacement before Q3 maintenance window.`,
        anomalyRef: 'dc-anomaly-2',
        workflowRepoRef: 'dc-repo-1',
        tags: ['ups', 'power', 'predictive'],
        upvotes: 27,
        comments: 3,
        createdAt: '2026-02-11T10:15:00Z',
        status: 'pending',
    },
    {
        id: 'dc-post-4',
        type: 'announcement',
        authorType: 'human',
        authorId: 'dc-tokyo',
        authorName: 'Tokyo HPC Center',
        title: 'Diesel Generator Test Protocol v2.1 — Now with NFPA-110 Compliance Export',
        content: `Updated the **Diesel Generator Test Protocol** to include automated NFPA-110 compliance reporting.\n\nNew in v2.1:\n- Automatic pass/fail log export in PDF format\n- Cooldown timer with thermal monitoring before shutdown\n- Battery charger current check added to pre-start checklist\n\nAll 4 DCs that adopted v2.0 will receive auto-update.`,
        workflowRepoRef: 'dc-repo-11',
        tags: ['generator', 'compliance', 'update'],
        upvotes: 19,
        comments: 2,
        createdAt: '2026-02-10T09:30:00Z',
        status: 'open',
    },
    {
        id: 'dc-post-5',
        type: 'insight',
        authorType: 'human',
        authorId: 'fahad-alrashid',
        authorName: 'Fahad Al-Rashid',
        title: 'Riyadh DC — Ambient 44°C But PUE Stable at 1.28 Thanks to Economizer Mode',
        content: `Sharing results from Riyadh during the summer peak last month.\n\nExternal ambient hit **44°C** — well above economizer cutoff, yet PUE held at **1.28** thanks to:\n- Adiabatic pre-cooling on air-side economizers\n- Dynamic chiller staging (1+2 at 60% load vs. 2+2 at 80%)\n- Night-time thermal storage charging (shifted ~1.2 MW to off-peak)\n\nHappy to share the chiller sequencing logic if anyone is interested.`,
        tags: ['pue', 'cooling', 'hot-climate', 'economizer'],
        upvotes: 44,
        comments: 7,
        createdAt: '2026-02-09T16:00:00Z',
        status: 'open',
    },
    {
        id: 'dc-post-6',
        type: 'announcement',
        authorType: 'human',
        authorId: 'dc-frankfurt',
        authorName: 'Frankfurt DC Campus',
        title: 'Server Hardware Failure Prediction — 23 Days Without Unplanned Downtime',
        content: `Milestone update: **23 consecutive days without unplanned server downtime** since deploying the Hardware Failure Prediction workflow.\n\nIn this period:\n- 4 drives replaced proactively (SMART threshold alerts)\n- 2 PSUs flagged for replacement before failure (thermal cycling pattern)\n- 1 memory stick replaced after correctable ECC spike trend\n\nEstimated savings vs. reactive replacement: **€62k** in avoided downtime costs.`,
        workflowRepoRef: 'dc-repo-3',
        tags: ['hardware', 'predictive', 'uptime'],
        upvotes: 53,
        comments: 6,
        createdAt: '2026-02-08T11:00:00Z',
        status: 'open',
    },
]

// ─── Anomalies ────────────────────────────────────────────────────────────
export const DC_MOCK_ANOMALIES: DetectedAnomaly[] = [
    {
        id: 'dc-anomaly-1',
        factoryId: 'dc-frankfurt',
        factoryName: 'Frankfurt DC Campus',
        equipmentId: 'eq-crac-c03',
        equipmentName: 'CRAC Unit CR-03 — Row C',
        equipmentType: 'Cooling',
        severity: 'critical',
        description: 'Supply air temperature rising (+4.2°C above setpoint). Fan speed at 98% but insufficient. Possible refrigerant charge issue or condenser fouling.',
        detectedAt: '2026-02-13T08:15:00Z',
        suggestedWorkflowId: 'dc-repo-4',
        suggestedWorkflowName: 'Rack Temperature Control',
        suggestedAction: 'Inspect CRAC CR-03 condenser coil and check refrigerant charge',
        status: 'pending',
        confidence: 0.94,
        remainingUsefulLife: '3 hours',
        estimatedCostIfIgnored: 52000,
        digitalTwinAssetId: 'crac-cr-03',
    },
    {
        id: 'dc-anomaly-2',
        factoryId: 'dc-newyork',
        factoryName: 'New York Exchange DC',
        equipmentId: 'eq-ups-3',
        equipmentName: 'UPS-3 Battery String — Room B',
        equipmentType: 'Power',
        severity: 'high',
        description: 'State of health at 67% (threshold: 80%). Float current elevated by 18%. Pattern matches progressive cell sulfation with 87% confidence.',
        detectedAt: '2026-02-09T14:20:00Z',
        suggestedWorkflowId: 'dc-repo-1',
        suggestedWorkflowName: 'UPS Battery Failure Detection',
        suggestedAction: 'Schedule battery string replacement within 72h, verify transfer switch operation',
        status: 'pending',
        confidence: 0.87,
        remainingUsefulLife: '6 months',
        estimatedCostIfIgnored: 18500,
        digitalTwinAssetId: 'ups-3',
    },
    {
        id: 'dc-anomaly-3',
        factoryId: 'dc-frankfurt',
        factoryName: 'Frankfurt DC Campus',
        equipmentId: 'eq-pdu-b7',
        equipmentName: 'PDU-B7 — Cabinet Row B',
        equipmentType: 'Power',
        severity: 'high',
        description: 'Phase A at 28.4A (circuit limit: 32A). Phase B at 9.1A. Load imbalance of 68%. Continued operation risks nuisance tripping.',
        detectedAt: '2026-02-13T06:40:00Z',
        suggestedWorkflowId: 'dc-repo-7',
        suggestedWorkflowName: 'PDU Load Balancing',
        suggestedAction: 'Migrate 2 high-draw servers from Phase A to Phase B circuits',
        status: 'pending',
        confidence: 0.96,
        remainingUsefulLife: '48 hours',
        estimatedCostIfIgnored: 9200,
        digitalTwinAssetId: 'pdu-b7',
    },
    {
        id: 'dc-anomaly-4',
        factoryId: 'dc-riyadh',
        factoryName: 'Riyadh Data Center',
        equipmentId: 'eq-crah-b3',
        equipmentName: 'CRAH Unit B-3 — Hall B',
        equipmentType: 'Cooling',
        severity: 'low',
        description: 'Supply temperature 2.1°C above setpoint. Air filter differential pressure at 185 Pa (change threshold: 200 Pa). Likely reduced airflow due to filter loading.',
        detectedAt: '2026-02-09T09:30:00Z',
        suggestedWorkflowId: 'dc-repo-2',
        suggestedWorkflowName: 'Cooling System Optimization',
        suggestedAction: 'Replace CRAH B-3 filters, check fan belt tension',
        status: 'pending',
        confidence: 0.72,
        remainingUsefulLife: '14 days',
        estimatedCostIfIgnored: 2800,
        digitalTwinAssetId: 'crah-b3',
    },
]

// ─── Changelog ────────────────────────────────────────────────────────────
export const DC_MOCK_CHANGELOG: ChangelogEntry[] = [
    { id: 'dc-cl-new-1', date: '2026-02-13T09:00:00Z', title: 'Global: UPS Battery Detection workflow now available', description: 'Frankfurt\'s proven UPS health monitoring workflow is available for all DCs. Estimated savings: $18k/asset per avoided outage.', factoryId: 'dc-frankfurt', workflowRepoId: 'dc-repo-1', type: 'release' },
    { id: 'dc-cl-1',     date: '2026-02-09T14:00:00Z', title: 'Tokyo: PUE Optimization v3.1 — 12% improvement over baseline', description: 'New chiller staging logic reduced energy overhead, saving $28k/month', factoryId: 'dc-tokyo', workflowRepoId: 'dc-repo-9', type: 'release' },
    { id: 'dc-cl-2',     date: '2026-02-08T16:30:00Z', title: 'Frankfurt: Hardware Prediction saved €62K this month', description: '23 days without unplanned downtime — 4 drives, 2 PSUs, 1 DIMM replaced proactively', factoryId: 'dc-frankfurt', type: 'insight' },
    { id: 'dc-cl-3',     date: '2026-02-07T10:00:00Z', title: 'Singapore: Capacity Planning Automation → procurement lead time −40%', description: 'Rack utilization alerts now trigger purchase orders 6 weeks before capacity breach', factoryId: 'dc-singapore', workflowRepoId: 'dc-repo-5', type: 'integration' },
    { id: 'dc-cl-4',     date: '2026-02-06T12:00:00Z', title: 'Cross-DC workflow adoption launched', description: 'Data centers can now adopt proven workflows from top performers across the network', type: 'improvement' },
    { id: 'dc-cl-5',     date: '2026-02-05T09:00:00Z', title: 'New York: PDU Load Balancing deployed — 3 near-trip events avoided', description: 'Automated load migration prevented circuit overload on 3 occasions this week', factoryId: 'dc-newyork', workflowRepoId: 'dc-repo-7', type: 'improvement' },
    { id: 'dc-cl-6',     date: '2026-02-04T14:30:00Z', title: 'Global: AI thermal prediction engine upgraded', description: 'Cross-DC thermal pattern matching now detects cooling failures 2h earlier on average', type: 'release' },
    { id: 'dc-cl-7',     date: '2026-02-03T11:00:00Z', title: 'São Paulo: Humidity Control published — available for adoption', description: 'Maintains ASHRAE A2 humidity envelope with 15% less HVAC energy consumption', factoryId: 'dc-saopaulo', workflowRepoId: 'dc-repo-12', type: 'release' },
    { id: 'dc-cl-8',     date: '2026-02-02T08:00:00Z', title: 'Alert: 3 high-severity anomalies require attention', description: 'AI monitoring flagged critical infrastructure issues across Frankfurt and New York', type: 'alert' },
]

// ─── Checklist steps for UPS replacement work order ──────────────────────
const DC_CHECKLIST_UPS: ChecklistStep[] = [
    {
        id: 'dc-step-1',
        order: 1,
        title: 'Notify NOC and Transfer Load',
        instructions: 'Notify Network Operations Center of planned maintenance window. Transfer UPS-3 protected load to UPS-4 via static bypass switch. Confirm load transfer on panel display. Document transfer time.',
        caution: 'Ensure UPS-4 has sufficient capacity before transferring. Total protected load must not exceed 80% of UPS-4 rating.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '15 min',
        completed: false,
    },
    {
        id: 'dc-step-2',
        order: 2,
        title: 'Inspect Battery String Connections',
        instructions: 'Open battery cabinet. Inspect all inter-cell connectors for corrosion, heat damage, or loose torque. Use torque wrench (spec: 4.5 Nm for M6 connectors). Check vent caps for electrolyte residue.',
        requiresPhoto: true,
        requiresSignoff: false,
        estimatedTime: '25 min',
        completed: false,
    },
    {
        id: 'dc-step-3',
        order: 3,
        title: 'Perform Individual Cell Voltage Test',
        instructions: 'Measure open-circuit voltage on each cell using calibrated multimeter. Log readings in DCIM system. Flag cells below 2.12V per cell for replacement. Compare against initial commissioning values.',
        caution: 'Battery terminals carry live DC voltage at all times. Always use insulated tools and wear PPE.',
        requiresPhoto: true,
        requiresSignoff: false,
        estimatedTime: '30 min',
        completed: false,
    },
    {
        id: 'dc-step-4',
        order: 4,
        title: 'Replace Degraded Battery Cells',
        instructions: 'Remove and replace identified degraded cells (Part: MK12-75 or equivalent per approved vendor list). Ensure replacement cells are from same production batch. Reconnect at specified torque. Verify polarity before energizing.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '60 min',
        completed: false,
    },
    {
        id: 'dc-step-5',
        order: 5,
        title: 'Equalization Charge and Capacity Test',
        instructions: 'Run UPS equalization charge cycle (approx. 8h). After charge, perform 25% discharge capacity test. Log result in DCIM. Confirm state-of-health reading >85% before returning UPS-3 to service.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '30 min (setup — test runs overnight)',
        completed: false,
    },
]

export const DC_EXECUTION_CHECKLIST: ExecutionChecklist = {
    id: 'dc-checklist-ups3-t2',
    workOrderId: 'dc-wo-0847',
    taskId: 'dc-task-0847-3',
    title: 'UPS-3 Battery String Inspection & Replacement',
    steps: DC_CHECKLIST_UPS,
}

// ─── Checklist for CRAC repair ────────────────────────────────────────────
const DC_CRAC_CHECKLIST: ChecklistStep[] = [
    {
        id: 'dc-step-k1',
        order: 1,
        title: 'Isolate CRAC Unit CR-03',
        instructions: 'Switch CR-03 to standby mode from BMS. Verify standby CRAC CR-04 picks up cooling load (confirm supply temp stable within 2 min). Lock out CR-03 main power isolator.',
        caution: 'Do not isolate CR-03 if CR-04 supply temperature exceeds 22°C — escalate to DC Manager.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '10 min',
        completed: true,
    },
    {
        id: 'dc-step-k2',
        order: 2,
        title: 'Condenser Coil Inspection',
        instructions: 'Inspect condenser coil fins for fouling, blockage, or mechanical damage. Photograph coil condition. Clean with coil cleaner if fouled (rinse thoroughly). Check fin alignment.',
        requiresPhoto: true,
        requiresSignoff: false,
        estimatedTime: '20 min',
        completed: false,
    },
    {
        id: 'dc-step-k3',
        order: 3,
        title: 'Refrigerant Circuit Check',
        instructions: 'Connect manifold gauges. Record suction and discharge pressures. Compare against R410A saturation table for ambient conditions. Check subcooling (target: 8–12°C) and superheat (target: 6–10°C).',
        caution: 'Only certified refrigeration technician may handle refrigerant. F-Gas regulations apply.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '25 min',
        completed: false,
    },
    {
        id: 'dc-step-k4',
        order: 4,
        title: 'Test Run and BMS Verification',
        instructions: 'Restore CR-03 to service via BMS. Monitor supply temperature for 10 minutes. Confirm ±0.5°C of setpoint. Verify BMS alert cleared and CR-04 returns to standby.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '15 min',
        completed: false,
    },
]

// ─── Tasks ────────────────────────────────────────────────────────────────
const DC_TASKS_CRAC: WorkOrderTask[] = [
    {
        id: 'dc-task-crac-1',
        number: 1,
        workOrderId: 'dc-wo-crac-01',
        type: 'investigation',
        title: 'Verify Thermal Signature — Row C Sensor Cross-Check',
        description: 'Cross-reference CR-03 sensor data with adjacent in-row cooling units and rack-mounted thermistors. Confirm anomaly is not sensor drift.',
        assignee: DC_MOCK_TEAM[1],
        assignedBy: DC_MOCK_TEAM[0],
        priority: 'high',
        status: 'completed',
        dependsOn: [],
        isBlocked: false,
        updates: [
            {
                id: 'dc-update-k1',
                author: DC_MOCK_TEAM[1],
                content: 'Confirmed. Three independent sensors in Row C show elevated inlet temps. Not sensor drift — CR-03 supply air is genuinely warm.',
                createdAt: '2026-02-13T09:00:00Z',
            },
        ],
        createdAt: '2026-02-13T08:50:00Z',
        updatedAt: '2026-02-13T09:00:00Z',
    },
    {
        id: 'dc-task-crac-2',
        number: 2,
        workOrderId: 'dc-wo-crac-01',
        type: 'execution',
        title: 'Inspect and Service CRAC CR-03',
        description: 'Perform condenser inspection and refrigerant circuit check per SOP-C-007.',
        assignee: DC_MOCK_TEAM[2],
        assignedBy: DC_MOCK_TEAM[1],
        priority: 'critical',
        status: 'in-progress',
        dependsOn: ['dc-task-crac-1'],
        isBlocked: false,
        checklist: DC_CRAC_CHECKLIST,
        updates: [],
        createdAt: '2026-02-13T09:05:00Z',
        updatedAt: '2026-02-13T09:05:00Z',
    },
]

const DC_TASKS_0847: WorkOrderTask[] = [
    {
        id: 'dc-task-0847-1',
        number: 1,
        workOrderId: 'dc-wo-0847',
        type: 'investigation',
        title: 'Investigate root cause of UPS-3 battery degradation',
        description: 'Review DCIM battery logs for UPS-3 over last 90 days. Cross-reference with temperature logs and discharge event history. Determine if degradation is age-related or caused by environmental/operational factors.',
        assignee: DC_MOCK_TEAM[1],
        assignedBy: DC_MOCK_TEAM[0],
        priority: 'high',
        status: 'completed',
        dependsOn: [],
        isBlocked: false,
        updates: [
            {
                id: 'dc-update-1',
                author: DC_MOCK_TEAM[1],
                content: 'Root cause confirmed: cell sulfation due to repeated partial-state-of-charge operation during last 3 power tests. Not an environmental issue.',
                createdAt: '2026-02-09T10:30:00Z',
            },
        ],
        createdAt: '2026-02-09T09:20:00Z',
        updatedAt: '2026-02-09T10:30:00Z',
    },
    {
        id: 'dc-task-0847-2',
        number: 2,
        workOrderId: 'dc-wo-0847',
        type: 'investigation',
        title: 'Procurement and transfer-load planning',
        description: 'Order replacement battery cells (Part: MK12-75, qty: 4). Coordinate with NOC for UPS-3 maintenance window. Confirm UPS-4 capacity headroom for load transfer.',
        assignee: DC_MOCK_TEAM[0],
        assignedBy: DC_MOCK_TEAM[0],
        priority: 'high',
        status: 'completed',
        dependsOn: ['dc-task-0847-1'],
        isBlocked: false,
        updates: [
            {
                id: 'dc-update-2',
                author: DC_MOCK_TEAM[0],
                content: 'Parts ordered. ETA 48h. NOC window confirmed for 2026-02-11 02:00–06:00 UTC. UPS-4 headroom verified at 34%.',
                createdAt: '2026-02-09T12:00:00Z',
            },
        ],
        createdAt: '2026-02-09T11:00:00Z',
        updatedAt: '2026-02-09T12:00:00Z',
    },
    {
        id: 'dc-task-0847-3',
        number: 3,
        workOrderId: 'dc-wo-0847',
        type: 'execution',
        title: 'Battery cell replacement and capacity test',
        description: 'Replace 4 degraded cells per SOP-P-047. Run equalization charge and 25% discharge capacity test. Update DCIM asset record.',
        assignee: DC_MOCK_TEAM[2],
        assignedBy: DC_MOCK_TEAM[0],
        priority: 'critical',
        status: 'in-progress',
        dependsOn: ['dc-task-0847-2'],
        isBlocked: false,
        checklist: DC_CHECKLIST_UPS,
        updates: [
            {
                id: 'dc-update-3a',
                author: DC_MOCK_TEAM[2],
                content: 'Load transferred to UPS-4. CR-03 isolated. Starting battery cell replacement.',
                createdAt: '2026-02-11T02:15:00Z',
            },
        ],
        createdAt: '2026-02-09T12:05:00Z',
        updatedAt: '2026-02-11T02:15:00Z',
    },
    {
        id: 'dc-task-0847-4',
        number: 4,
        workOrderId: 'dc-wo-0847',
        type: 'verification',
        title: 'Validate UPS-3 state-of-health and return to service',
        description: 'After capacity test completes, confirm SoH > 85%. Verify transfer switch operation. Update DCIM battery health record and set next inspection date. Clear maintenance alarm in BMS.',
        assignee: DC_MOCK_TEAM[3],
        assignedBy: DC_MOCK_TEAM[0],
        priority: 'high',
        status: 'pending',
        dependsOn: ['dc-task-0847-3'],
        isBlocked: true,
        updates: [],
        createdAt: '2026-02-09T12:10:00Z',
        updatedAt: '2026-02-09T12:10:00Z',
    },
]

// ─── Work Orders ──────────────────────────────────────────────────────────
export const DC_MOCK_WORK_ORDER_CRAC: WorkOrderCard = {
    id: 'dc-wo-crac-01',
    number: 'WO-2026-0912',
    title: 'CRAC CR-03 Cooling Failure — Row C',
    description: 'Critical thermal anomaly detected in Frankfurt DC Row C. CRAC CR-03 supply air temperature 7.1°C above setpoint. Rack C-14 inlet at 34.1°C. AI confidence 94% for condenser fouling or refrigerant issue. Immediate inspection required.',
    equipmentId: 'eq-crac-c03',
    equipmentName: 'CRAC Unit CR-03 — Row C',
    status: 'in-progress',
    priority: 'critical',
    createdAt: '2026-02-13T08:45:00Z',
    owner: DC_MOCK_TEAM[1],
    team: [DC_MOCK_TEAM[1], DC_MOCK_TEAM[2]],
    tags: ['cooling', 'crac', 'critical', 'thermal'],
    linkedAnomalyId: 'dc-anomaly-1',
    tasks: DC_TASKS_CRAC,
    facility: 'Frankfurt DC Campus',
}

export const DC_MOCK_WORK_ORDER_0847: WorkOrderCard = {
    id: 'dc-wo-0847',
    number: 'WO-2026-0847',
    title: 'UPS-3 Battery String Replacement — NYC DC',
    description: 'Critical battery health degradation on UPS-3 in New York Exchange DC. State of health at 67% (threshold: 80%). Float current elevated 18%. Pattern matches cell sulfation. Uptime risk if not addressed: estimated 6-month window to failure with potential for unexpected switchover under load.',
    equipmentId: 'eq-ups-3',
    equipmentName: 'UPS-3 Battery String — Room B',
    status: 'in-progress',
    priority: 'critical',
    createdAt: '2026-02-09T09:18:00Z',
    owner: DC_MOCK_TEAM[0],
    team: [DC_MOCK_TEAM[0], DC_MOCK_TEAM[1], DC_MOCK_TEAM[2], DC_MOCK_TEAM[3]],
    tags: ['ups', 'power', 'battery', 'critical'],
    linkedAnomalyId: 'dc-anomaly-2',
    tasks: DC_TASKS_0847,
    facility: 'New York Exchange DC',
}

const DC_MOCK_WORK_ORDER_PDU: WorkOrderCard = {
    id: 'dc-wo-0839',
    number: 'WO-2026-0839',
    title: 'PDU-B7 Phase Imbalance — Cabinet Row B',
    description: 'Phase A at 89% of circuit capacity. Load imbalance 68% between Phase A and B. Risk of nuisance tripping under peak load.',
    equipmentId: 'eq-pdu-b7',
    equipmentName: 'PDU-B7 — Cabinet Row B',
    status: 'in-progress',
    priority: 'high',
    createdAt: '2026-02-13T07:00:00Z',
    owner: DC_MOCK_TEAM[1],
    team: [DC_MOCK_TEAM[1], DC_MOCK_TEAM[2]],
    tags: ['power', 'pdu', 'load-balance'],
    linkedAnomalyId: 'dc-anomaly-3',
    tasks: [],
    facility: 'Frankfurt DC Campus',
}

const DC_MOCK_WORK_ORDER_CRAH: WorkOrderCard = {
    id: 'dc-wo-0815',
    number: 'WO-2026-0815',
    title: 'CRAH B-3 Filter Replacement — Riyadh DC',
    description: 'Filter differential pressure at 185 Pa approaching change threshold. Supply temp 2.1°C above setpoint.',
    equipmentId: 'eq-crah-b3',
    equipmentName: 'CRAH Unit B-3 — Hall B',
    status: 'open',
    priority: 'low',
    createdAt: '2026-02-09T09:30:00Z',
    owner: DC_MOCK_TEAM[2],
    team: [DC_MOCK_TEAM[2]],
    tags: ['cooling', 'crah', 'filter'],
    linkedAnomalyId: 'dc-anomaly-4',
    tasks: [],
    facility: 'Riyadh Data Center',
}

const DC_MOCK_WORK_ORDER_FIBER: WorkOrderCard = {
    id: 'dc-wo-0803',
    number: 'WO-2026-0803',
    title: 'Fiber Cable Audit — MDA-to-IDA Links',
    description: 'Quarterly fiber link health check between Main Distribution Area and Intermediate Distribution Areas.',
    equipmentId: 'eq-fiber-mda',
    equipmentName: 'MDA Fiber Patch Panel',
    status: 'resolved',
    priority: 'medium',
    createdAt: '2026-02-05T08:15:00Z',
    resolvedAt: '2026-02-05T16:30:00Z',
    owner: DC_MOCK_TEAM[2],
    team: [DC_MOCK_TEAM[2]],
    tags: ['fiber', 'network', 'audit'],
    tasks: [],
    facility: 'Frankfurt DC Campus',
    costSaved: 3200,
}

const DC_MOCK_WORK_ORDER_FIRMWARE: WorkOrderCard = {
    id: 'dc-wo-0798',
    number: 'WO-2026-0798',
    title: 'BIOS Firmware Update — Batch SGP-Q1',
    description: 'Planned firmware update for 48 servers in Singapore Cloud Hub. Includes critical security patch CVE-2025-1234.',
    equipmentId: 'eq-servers-sgp',
    equipmentName: 'Server Rack Group — Singapore Q1',
    status: 'resolved',
    priority: 'medium',
    createdAt: '2026-02-04T10:00:00Z',
    resolvedAt: '2026-02-04T14:45:00Z',
    owner: DC_MOCK_TEAM[2],
    team: [DC_MOCK_TEAM[2]],
    tags: ['firmware', 'security', 'scheduled'],
    tasks: [],
    facility: 'Singapore Cloud Hub',
    costSaved: 1800,
}

const DC_MOCK_WORK_ORDER_GENERATOR: WorkOrderCard = {
    id: 'dc-wo-0785',
    number: 'WO-2026-0785',
    title: 'Diesel Generator Monthly Load Test — Frankfurt',
    description: 'Mandatory monthly load bank test for GEN-01 and GEN-02 per NFPA-110. All 4 ATS transfer switches to be exercised.',
    equipmentId: 'eq-gen-fra',
    equipmentName: 'Diesel Generator GEN-01/02',
    status: 'closed',
    priority: 'low',
    createdAt: '2026-02-03T07:00:00Z',
    resolvedAt: '2026-02-03T12:00:00Z',
    owner: DC_MOCK_TEAM[3],
    team: [DC_MOCK_TEAM[3]],
    tags: ['generator', 'compliance', 'inspection'],
    tasks: [],
    facility: 'Frankfurt DC Campus',
}

const DC_MOCK_WORK_ORDER_THERMAL: WorkOrderCard = {
    id: 'dc-wo-0772',
    number: 'WO-2026-0772',
    title: 'Thermal Imaging Scan — Electrical Distribution',
    description: 'Quarterly IR scan of all main switchboards and transformer connections.',
    equipmentId: 'eq-sw-main',
    equipmentName: 'Main Switchboard — Room A',
    status: 'closed',
    priority: 'low',
    createdAt: '2026-02-02T08:30:00Z',
    resolvedAt: '2026-02-02T11:15:00Z',
    owner: DC_MOCK_TEAM[1],
    team: [DC_MOCK_TEAM[1]],
    tags: ['electrical', 'thermal', 'inspection'],
    tasks: [],
    facility: 'Frankfurt DC Campus',
}

const DC_MOCK_WORK_ORDER_CABLE: WorkOrderCard = {
    id: 'dc-wo-0765',
    number: 'WO-2026-0765',
    title: 'Cable Management Remediation — Row D',
    description: 'Resolve cable congestion in Row D rear cable trays identified during last audit.',
    equipmentId: 'eq-row-d-cables',
    equipmentName: 'Cable Tray — Row D',
    status: 'closed',
    priority: 'low',
    createdAt: '2026-02-01T06:00:00Z',
    resolvedAt: '2026-02-01T09:30:00Z',
    owner: DC_MOCK_TEAM[2],
    team: [DC_MOCK_TEAM[2]],
    tags: ['cable', 'infrastructure', 'maintenance'],
    tasks: [],
    facility: 'Frankfurt DC Campus',
}

const DC_MOCK_WORK_ORDER_ACCESS: WorkOrderCard = {
    id: 'dc-wo-0758',
    number: 'WO-2026-0758',
    title: 'Access Control Audit — Cage B',
    description: 'Quarterly review of badge access logs and CCTV retention for Cage B colocation area.',
    equipmentId: 'eq-access-cage-b',
    equipmentName: 'Access Control System — Cage B',
    status: 'closed',
    priority: 'medium',
    createdAt: '2026-01-31T07:30:00Z',
    resolvedAt: '2026-01-31T13:00:00Z',
    owner: DC_MOCK_TEAM[1],
    team: [DC_MOCK_TEAM[1]],
    tags: ['security', 'compliance', 'access'],
    tasks: [],
    facility: 'Frankfurt DC Campus',
}

export const DC_ALL_MOCK_WORK_ORDERS: WorkOrderCard[] = [
    DC_MOCK_WORK_ORDER_CRAC,
    DC_MOCK_WORK_ORDER_0847,
    DC_MOCK_WORK_ORDER_PDU,
    DC_MOCK_WORK_ORDER_CRAH,
    DC_MOCK_WORK_ORDER_FIBER,
    DC_MOCK_WORK_ORDER_FIRMWARE,
    DC_MOCK_WORK_ORDER_GENERATOR,
    DC_MOCK_WORK_ORDER_THERMAL,
    DC_MOCK_WORK_ORDER_CABLE,
    DC_MOCK_WORK_ORDER_ACCESS,
]

// ─── Activity Entries for WO-0847 ─────────────────────────────────────────
export const DC_MOCK_ACTIVITY_ENTRIES: ActivityEntry[] = [
    {
        id: 'dc-act-1',
        workOrderId: 'dc-wo-0847',
        action: 'anomaly-detected',
        actor: { id: 'ai-monitor', name: 'NYC AI Monitor', role: 'AI Agent' },
        description: 'Anomaly detected: UPS-3 battery state-of-health degradation',
        details: 'SoH dropped to 67%. Float current +18% above baseline. Confidence: 87%.',
        timestamp: '2026-02-09T09:15:00Z',
        metadata: { anomalyId: 'dc-anomaly-2', confidence: 0.87 },
    },
    {
        id: 'dc-act-2',
        workOrderId: 'dc-wo-0847',
        action: 'work-order-created',
        actor: { id: 'ai-monitor', name: 'NYC AI Monitor', role: 'AI Agent' },
        description: 'Work order WO-2026-0847 created automatically',
        details: 'Priority: Critical. Assigned to Sarah Chen (DC Operations Manager).',
        timestamp: '2026-02-09T09:18:00Z',
    },
    {
        id: 'dc-act-3',
        workOrderId: 'dc-wo-0847',
        action: 'task-assigned',
        actor: DC_MOCK_TEAM[0],
        description: 'Investigation task assigned to Omar Khalid',
        details: 'Task #1: Investigate root cause of battery degradation',
        timestamp: '2026-02-09T09:20:00Z',
    },
]

// ─── Discussion Comments ──────────────────────────────────────────────────
export const DC_MOCK_DISCUSSION: DiscussionComment[] = [
    {
        id: 'dc-comment-1',
        workOrderId: 'dc-wo-0847',
        author: DC_MOCK_TEAM[1],
        content: 'Root cause confirmed: partial-state-of-charge cycling. This is a known issue with sites that run weekly capacity tests at 10% load — insufficient to prevent sulfation.',
        mentions: [],
        createdAt: '2026-02-09T10:35:00Z',
    },
    {
        id: 'dc-comment-2',
        workOrderId: 'dc-wo-0847',
        author: DC_MOCK_TEAM[0],
        content: 'Good catch. We should update the test protocol to run at 25% load minimum and add an equalization charge quarterly. Raising this with the standards team.',
        mentions: [],
        createdAt: '2026-02-09T11:00:00Z',
    },
]

// ─── AI Recommendation ────────────────────────────────────────────────────
export const DC_MOCK_AI_RECOMMENDATION: AIAgentRecommendation = {
    id: 'dc-ai-rec-1',
    workOrderId: 'dc-wo-0847',
    generatedAt: '2026-02-09T13:30:00Z',
    status: 'pending-review',
    workflow: {
        id: 'wf-gen-ups-battery-monitor',
        name: 'Automated UPS Battery Health Monitor',
        description: 'Proactive monitoring workflow that detects PSoC-induced battery degradation before critical failure. Triggers maintenance alert when float current exceeds threshold or SoH drops below 80%.',
        version: '1.0.0-draft',
        trigger: {
            type: 'sensor-threshold',
            description: 'Monitor UPS battery state-of-health and float current continuously',
            config: { metric: 'battery_soh', threshold: 80, unit: 'percent', window: '24h' },
        },
        conditions: [
            {
                type: 'correlation-check',
                description: 'Verify capacity test load is sufficient (min 25%) to prevent false positives',
                config: { correlateWith: 'capacity_test_load', minCorrelation: 0.8 },
            },
            {
                type: 'persistence-check',
                description: 'Confirm degradation trend persists across 3 consecutive measurement cycles',
                config: { minOccurrences: 3, timeWindow: '72h' },
            },
        ],
        actions: [
            {
                type: 'create-work-order',
                description: 'Auto-create maintenance work order for battery inspection',
                config: { priority: 'high', template: 'battery-replacement', assignTo: 'dc-operations-lead' },
            },
            {
                type: 'notify-team',
                description: 'Alert DC operations team',
                config: { channel: 'dc-operations', urgency: 'high' },
            },
            {
                type: 'reserve-parts',
                description: 'Pre-reserve replacement cells from inventory',
                config: { partNumber: 'MK12-75', quantity: 4 },
            },
        ],
        generatedFrom: {
            anomalyPattern: 'ups-battery-degradation-dc-wo-0847',
            sensorThresholds: [
                { metric: 'battery_soh', operator: '<', value: 80, unit: 'percent' },
                { metric: 'float_current', operator: '>', value: 2.1, unit: 'amperes' },
            ],
            correlations: [
                'PSoC-induced sulfation follows predictable SoH decay curve detectable 4-8 months before failure',
                'Elevated ambient temperature (+2.1°C) accelerates sulfation by ~15% — Room B requires cooling review',
            ],
        },
    },
    sop: {
        id: 'sop-gen-ups-battery',
        title: 'UPS Battery Cell Inspection and Replacement Procedure',
        version: '1.0.0-draft',
        description: 'Generated from DC-WO-0847 resolution. Standard procedure for inspecting and replacing UPS battery cells in datacenter environments.',
        basedOn: 'DC-WO-0847 resolution by Omar Khalid and Priya Sharma',
        steps: [
            { order: 1, title: 'Transfer load to UPS-4', instructions: 'Notify NOC. Transfer UPS-3 load via static bypass.', requiresPhoto: true, requiresSignoff: true, estimatedTime: '15 min' },
            { order: 2, title: 'Cell voltage survey', instructions: 'Measure open-circuit voltage on all cells. Flag cells below 2.12V.', requiresPhoto: true, requiresSignoff: false, estimatedTime: '30 min' },
            { order: 3, title: 'Replace degraded cells', instructions: 'Replace flagged cells with MK12-75 (same batch). Torque to 4.5 Nm.', requiresPhoto: true, requiresSignoff: true, estimatedTime: '60 min' },
            { order: 4, title: 'Equalization charge + capacity test', instructions: 'Run 8h equalization charge. Perform 25% load test. Log SoH.', requiresPhoto: true, requiresSignoff: true, estimatedTime: '8h (overnight)', caution: 'Do not interrupt equalization charge once started.' },
            { order: 5, title: 'Return to service', instructions: 'Confirm SoH > 85%. Transfer load back from UPS-4. Update DCIM.', requiresPhoto: true, requiresSignoff: true, estimatedTime: '15 min' },
        ],
        safetyNotes: [
            'Battery terminals are live at all times — use insulated tools',
            'Wear PPE: safety glasses, insulated gloves, acid-resistant apron',
            'Ensure room ventilation is active during battery work (hydrogen off-gassing risk)',
        ],
        partsRequired: [
            { partName: 'Lead-Acid Battery Cell', partNumber: 'MK12-75', quantity: 4 },
            { partName: 'Inter-cell Connector Washer', partNumber: 'WSH-M6-LEAD', quantity: 8 },
        ],
        estimatedDuration: '9h 30min (includes overnight charge)',
        toolsRequired: ['Calibrated multimeter', 'Torque wrench (M6)', 'Insulated socket set', 'Hydrometer', 'Insulated gloves', 'Safety glasses'],
    },
    summary: {
        patternDetected: 'PSoC-induced sulfation follows predictable SoH decay curve, detectable 4–8 months before failure through float current monitoring',
        dataSourcesUsed: [
            'UPS-3 DCIM battery logs (90 days)',
            'Capacity test history (24 months)',
            'Ambient temperature logs — Room B',
            'Manufacturer degradation model (Vertiv GXYDN)',
        ],
        confidenceScore: 0.87,
        estimatedPreventionValue: 18500,
        estimatedEarlyDetection: '4–8 months before critical failure',
        applicableFacilities: ['Frankfurt DC Campus', 'New York Exchange DC', 'Riyadh Data Center'],
    },
}
