[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncua>=1.1.8",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.135.1",
    "sqlmodel>=0.0.37",
    "vllm>=0.16.0",
    "accelerate>=0.34.0",
    "pypdf>=6.8.0",
    "python-docx>=1.2.0",
    "openpyxl>=3.1.5",
    "xlrd>=2.0.2",
    "python-pptx>=1.0.2",
    "beautifulsoup4>=4.14.3",
    "striprtf>=0.0.29",
    "ebooklib>=0.20",
    "sentence-transformers>=5.2.3",
]
